pipeline {
    agent {
        docker {
            image 'ruby'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Preparando Ambiente') {
            steps {
                sh 'cd api && bundle install'
            }
        }
        stage('Testando') {
            steps {
                sh 'cd api && rspec'
            }
        }
    }
}