pipeline {
    agent {
        docker {
            image 'henriquecervi/ruby-web-agent'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Preparando Ambiente') {
            steps {
                sh 'cd web && bundle install'
            }
        }
        stage('Testando') {
            steps {
                sh 'cd web && rake local_seeds'                
            }
        }
    }
    post{
        always {
            allure includeProperties: false, jdk: '', results: [[path: 'web/logs']]
        }
    }
}