pipeline {
    agent {
        docker {
            image 'ruby'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Preparando Ambiente') {
            steps {
                sh 'cd web && bundle install'
            }
        }
        stage('Testando') {
            steps {
                sh 'cd web && cucumber'                
            }
        }
    }
    post{
        always {
            junit 'web/logs/result.json'
        }
    }
}